### ISSUE TITLE
Render URL's as clickable links in imported events

### ISSUE THREAD

**Issue by samuk** [humhub-contrib/external_calendar#40]
![imported-event](https://user-images.githubusercontent.com/400875/207952292-59689896-ba3e-4ff1-b132-8423d6777c5d.png)
In imported events turn links into clickable links.

I'm using this service to turn Eventbrite into Ical https://eb-to-ical.daylightpirates.org/

The resulting events include a URL, but it is not clickable

**Comment by funkycram** [comment]
@luke- what do you think about this PR? https://github.com/humhub-contrib/external_calendar/pull/45/files
It's a modified regex of https://stackoverflow.com/questions/4217406/php-add-link-to-a-url-in-a-string/4217452#4217452 adding some missing chars described on https://perishablepress.com/stop-using-unsafe-characters-in-urls/

**Comment by luke-** [comment]
@funkycram Can you please try somthing like this:

```
     <?= (new \cebe\markdown\GithubMarkdown())->parse(humhub\libs\Html::encode($description)); ?>
```

**Comment by funkycram** [comment]
Thanks @luke- for the suggestion!
This approach is different as it parse all the text to format markdown code, which is not conventional in calendar event descriptions other than Humhub.
But even so, it works well, and I don't think it's a problem when markdown is not used, and it can be great to know that using markdown will be nicely formatted on Humhub!

I had to change slightly the code to `nl2br((new \cebe\markdown\GithubMarkdown())->parse($description))`, because:
- `Html::encode` encodes the URL which is not good (e.g. for the `&`char)
- line breaks where missing again

See my new commit to the PR: https://github.com/humhub-contrib/external_calendar/pull/45/files

**Comment by luke-** [comment]
@funkycram 

Ah ok, for newlines i would prefer:

```
// on the top of the view file
$descriptionParser = new GithubMarkdown();
$descriptionParser->enableNewlines = true;
```

``` 
<p><?= $descriptionParser->parse($description)) ?></p>
```

**Comment by funkycram** [comment]
Thanks! I haven't seen this property, much better!
Commit done.
